In [12]:
import tensorflow as tf
import numpy as np

#### 1. tf.constant

In [7]:
# index (区间为左闭右开)

arr = tf.constant([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr[:, 1:])
print(arr[..., 1])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


In [10]:
# ops

print(arr + 10)
print(tf.square(arr))
# todo 转置矩阵
print(arr @ tf.transpose(arr))

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [18]:
# numpy conversion

print(arr.numpy())
arr_np = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_np)

print(np.square(arr))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [22]:
# Scalars (0 维向量/常量)

arr = tf.constant(3.1415)
print(arr)
print(arr.numpy())
print(arr.shape)


tf.Tensor(3.1415, shape=(), dtype=float32)
3.1415
()


In [25]:
# string

str = tf.constant("hello")
print(str)
print(tf.strings.length(str))
print(tf.strings.unicode_decode(str, 'UTF-8'))

tf.Tensor(b'hello', shape=(), dtype=string)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([104 101 108 108 111], shape=(5,), dtype=int32)


In [29]:
# strings

strs = tf.constant(["milk", "coffee", "tea"])
print(strs)
print(tf.strings.length(strs))
print(tf.strings.unicode_decode(strs, 'UTF-8'))

tf.Tensor([b'milk' b'coffee' b'tea'], shape=(3,), dtype=string)
tf.Tensor([4 6 3], shape=(3,), dtype=int32)
<tf.RaggedTensor [[109, 105, 108, 107], [99, 111, 102, 102, 101, 101], [116, 101, 97]]>


In [34]:
# ragged tensor (不规则的矩阵)

r1 = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41]])
print(r1[1])
print(r1[0:1])

tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[11, 12]]>


In [39]:
# ops on ragged tensor

r2 = tf.ragged.constant([[51, 52], [], [71]])
# 直接拼接
print(tf.concat([r1, r2], axis=0))

r3 = tf.ragged.constant([[13, 14], [2], [0]])
# 行内拼接
print(tf.concat([r2, r3], axis=1))

print(r3.to_tensor())

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [71]]>
<tf.RaggedTensor [[51, 52, 13, 14], [2], [71, 0]]>
tf.Tensor(
[[13 14]
 [ 2  0]
 [ 0  0]], shape=(3, 2), dtype=int32)


In [42]:
# sparse tensor

s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[6, 7, 8],
                    dense_shape=[3, 4])
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([6 7 8], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0 6 0 0]
 [7 0 0 0]
 [0 0 0 8]], shape=(3, 4), dtype=int32)


#### 2. tf.Variable

In [45]:
v = tf.Variable([[1, 2, 3], [4, 5, 6]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [49]:
# assign value

v.assign(2 * v)
print(v.numpy())
v[0, 1].assign(42)
print(v.numpy())
v[1].assign([0, 0, 1])
print(v.numpy())

[[16 84 48]
 [14 16 18]]
[[16 42 48]
 [14 16 18]]
[[16 42 48]
 [ 0  0  1]]
