##### Copyright 2018 The TensorFlow Authors.


In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 使用 tf.data 加载文本数据

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://tensorflow.google.cn/tutorials/load_data/text"><img src="https://tensorflow.google.cn/images/tf_logo_32px.png" />在 TensorFlow.org 上查看</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/load_data/text.ipynb"><img src="https://tensorflow.google.cn/images/colab_logo_32px.png" />在 Google Colab 上运行</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/load_data/text.ipynb"><img src="https://tensorflow.google.cn/images/GitHub-Mark-32px.png" />查看 GitHub 上的资源</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/zh-cn/tutorials/load_data/text.ipynb"><img src="https://tensorflow.google.cn/images/download_logo_32px.png" />下载 notebook</a>
  </td>
</table>

Note: 我们的 TensorFlow 社区翻译了这些文档。因为社区翻译是尽力而为， 所以无法保证它们是最准确的，并且反映了最新的
[官方英文文档](https://tensorflow.google.cn/?hl=en)。如果您有改进此翻译的建议， 请提交 pull request 到
[tensorflow/docs](https://github.com/tensorflow/docs) GitHub 仓库。要志愿地撰写或者审核译文，请加入
[docs-zh-cn@tensorflow.org Google Group](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-zh-cn)。

本教程为你提供了一个如何使用 `tf.data.TextLineDataset` 来加载文本文件的示例。`TextLineDataset` 通常被用来以文本文件构建数据集（原文件中的一行为一个样本) 。这适用于大多数的基于行的文本数据（例如，诗歌或错误日志) 。下面我们将使用相同作品（荷马的伊利亚特）三个不同版本的英文翻译，然后训练一个模型来通过单行文本确定译者。


## 环境搭建

In [2]:
import tensorflow as tf

import tensorflow_datasets as tfds
import os

三个版本的翻译分别来自于:

 - [William Cowper](https://en.wikipedia.org/wiki/William_Cowper) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/cowper.txt)

 - [Edward, Earl of Derby](https://en.wikipedia.org/wiki/Edward_Smith-Stanley,_14th_Earl_of_Derby) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/derby.txt)

- [Samuel Butler](https://en.wikipedia.org/wiki/Samuel_Butler_%28novelist%29) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/butler.txt)

本教程中使用的文本文件已经进行过一些典型的预处理，主要包括删除了文档页眉和页脚，行号，章节标题。请下载这些已经被局部改动过的文件。


In [3]:
DIRECTORY_URL = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
FILE_NAMES = ['cowper.txt', 'derby.txt', 'butler.txt']

for name in FILE_NAMES:
  text_dir = tf.keras.utils.get_file(name, origin=DIRECTORY_URL+name)
  
parent_dir = os.path.dirname(text_dir)

parent_dir

  8192/815980 [..............................] - ETA: 0s

819200/815980 [==============================] - 0s 0us/step


  8192/809730 [..............................] - ETA: 0s

811008/809730 [==============================] - 0s 0us/step


  8192/807992 [..............................] - ETA: 0s

811008/807992 [==============================] - 0s 0us/step


'/home/kbuilder/.keras/datasets'

## 将文本加载到数据集中

迭代整个文件，将整个文件加载到自己的数据集中。

每个样本都需要单独标记，所以请使用 `tf.data.Dataset.map` 来为每个样本设定标签。这将迭代数据集中的每一个样本并且返回（ `example, label` ）对。

In [4]:
def labeler(example, index):
  return example, tf.cast(index, tf.int64)  

labeled_data_sets = []

for i, file_name in enumerate(FILE_NAMES):
  lines_dataset = tf.data.TextLineDataset(os.path.join(parent_dir, file_name))
  labeled_dataset = lines_dataset.map(lambda ex: labeler(ex, i))
  labeled_data_sets.append(labeled_dataset)

将这些标记的数据集合并到一个数据集中，然后对其进行随机化操作。


In [5]:
BUFFER_SIZE = 50000
BATCH_SIZE = 64
TAKE_SIZE = 5000

In [6]:
all_labeled_data = labeled_data_sets[0]
for labeled_dataset in labeled_data_sets[1:]:
  all_labeled_data = all_labeled_data.concatenate(labeled_dataset)
  
all_labeled_data = all_labeled_data.shuffle(
    BUFFER_SIZE, reshuffle_each_iteration=False)

你可以使用 `tf.data.Dataset.take` 与 `print` 来查看 `(example, label)` 对的外观。`numpy` 属性显示每个 Tensor 的值。

In [7]:
for ex in all_labeled_data.take(5):
  print(ex)

(<tf.Tensor: shape=(), dtype=string, numpy=b'To Ida; in his presence once arrived,'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b"Such now appears th' o'er-ruling sov'reign will">, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Them so prepared the King of men beheld'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'mourn you, but the eddies of Scamander shall bear you into the broad'>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'there was no life left in him.'>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)


## 将文本编码成数字

机器学习基于的是数字而非文本，所以字符串需要被转化成数字列表。
为了达到此目的，我们需要构建文本与整数的一一映射。

### 建立词汇表


首先，通过将文本标记为单独的单词集合来构建词汇表。在 TensorFlow 和 Python 中均有很多方法来达成这一目的。在本教程中:

1. 迭代每个样本的 `numpy` 值。
2. 使用 `tfds.features.text.Tokenizer` 来将其分割成 `token`。
3. 将这些 `token` 放入一个 Python 集合中，借此来清除重复项。
4. 获取该词汇表的大小以便于以后使用。


In [8]:
tokenizer = tfds.features.text.Tokenizer()

vocabulary_set = set()
for text_tensor, _ in all_labeled_data:
  some_tokens = tokenizer.tokenize(text_tensor.numpy())
  vocabulary_set.update(some_tokens)

vocab_size = len(vocabulary_set)
vocab_size

17178

### 样本编码

通过传递 `vocabulary_set` 到 `tfds.features.text.TokenTextEncoder` 来构建一个编码器。编码器的 `encode` 方法传入一行文本，返回一个整数列表。

In [9]:
encoder = tfds.features.text.TokenTextEncoder(vocabulary_set)

你可以尝试运行这一行代码并查看输出的样式。

In [10]:
example_text = next(iter(all_labeled_data))[0].numpy()
print(example_text)

b'To Ida; in his presence once arrived,'


In [11]:
encoded_example = encoder.encode(example_text)
print(encoded_example)

[15746, 11433, 8394, 9006, 379, 3463, 17072]


现在，在数据集上运行编码器（通过将编码器打包到 `tf.py_function` 并且传参至数据集的 `map` 方法的方式来运行）。 

In [12]:
def encode(text_tensor, label):
  encoded_text = encoder.encode(text_tensor.numpy())
  return encoded_text, label

def encode_map_fn(text, label):
  # py_func doesn't set the shape of the returned tensors.
  encoded_text, label = tf.py_function(encode, 
                                       inp=[text, label], 
                                       Tout=(tf.int64, tf.int64))

  # `tf.data.Datasets` work best if all components have a shape set
  #  so set the shapes manually: 
  encoded_text.set_shape([None])
  label.set_shape([])

  return encoded_text, label


all_encoded_data = all_labeled_data.map(encode_map_fn)

## 将数据集分割为测试集和训练集且进行分支

使用 `tf.data.Dataset.take` 和 `tf.data.Dataset.skip` 来建立一个小一些的测试数据集和稍大一些的训练数据集。

在数据集被传入模型之前，数据集需要被分批。最典型的是，每个分支中的样本大小与格式需要一致。但是数据集中样本并不全是相同大小的（每行文本字数并不相同）。因此，使用 `tf.data.Dataset.padded_batch`（而不是 `batch` ）将样本填充到相同的大小。

In [13]:
train_data = all_encoded_data.skip(TAKE_SIZE).shuffle(BUFFER_SIZE)
train_data = train_data.padded_batch(BATCH_SIZE)

test_data = all_encoded_data.take(TAKE_SIZE)
test_data = test_data.padded_batch(BATCH_SIZE)

现在，test_data 和 train_data 不是（ `example, label` ）对的集合，而是批次的集合。每个批次都是一对（*多样本*, *多标签* ），表示为数组。


In [14]:
sample_text, sample_labels = next(iter(test_data))

sample_text[0], sample_labels[0]

(<tf.Tensor: shape=(16,), dtype=int64, numpy=
 array([15746, 11433,  8394,  9006,   379,  3463, 17072,     0,     0,
            0,     0,     0,     0,     0,     0,     0])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

由于我们引入了一个新的 token 来编码（填充零），因此词汇表大小增加了一个。

In [15]:
vocab_size += 1

## 建立模型


In [16]:
model = tf.keras.Sequential()

第一层将整数表示转换为密集矢量嵌入。更多内容请查阅 [Word Embeddings](../../tutorials/sequences/word_embeddings) 教程。

In [17]:
model.add(tf.keras.layers.Embedding(vocab_size, 64))

下一层是 [LSTM](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) 层，它允许模型利用上下文中理解单词含义。 LSTM 上的双向包装器有助于模型理解当前数据点与其之前和之后的数据点的关系。


In [18]:
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))

最后，我们将获得一个或多个紧密连接的层，其中最后一层是输出层。输出层输出样本属于各个标签的概率，最后具有最高概率的分类标签即为最终预测结果。


In [19]:
# 一个或多个紧密连接的层
# 编辑 `for` 行的列表去检测层的大小
for units in [64, 64]:
  model.add(tf.keras.layers.Dense(units, activation='relu'))

# 输出层。第一个参数是标签个数。
model.add(tf.keras.layers.Dense(3, activation='softmax'))

最后，编译这个模型。对于一个 softmax 分类模型来说，通常使用 `sparse_categorical_crossentropy` 作为其损失函数。你可以尝试其他的优化器，但是 `adam` 是最常用的。

In [20]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

## 训练模型

利用提供的数据训练出的模型有着不错的精度（大约 83% ）。

In [21]:
model.fit(train_data, epochs=3, validation_data=test_data)

Epoch 1/3


      1/Unknown - 0s 454us/step - loss: 1.0981 - accuracy: 0.3750

      5/Unknown - 0s 12ms/step - loss: 1.0867 - accuracy: 0.4375 

     11/Unknown - 0s 10ms/step - loss: 1.0735 - accuracy: 0.4205

     17/Unknown - 0s 10ms/step - loss: 1.0577 - accuracy: 0.4053

     23/Unknown - 0s 10ms/step - loss: 1.0394 - accuracy: 0.4062

     29/Unknown - 0s 10ms/step - loss: 1.0136 - accuracy: 0.4413

     35/Unknown - 0s 10ms/step - loss: 0.9783 - accuracy: 0.4728

     41/Unknown - 0s 10ms/step - loss: 0.9465 - accuracy: 0.4954

     47/Unknown - 0s 10ms/step - loss: 0.9045 - accuracy: 0.5123

     52/Unknown - 1s 10ms/step - loss: 0.8874 - accuracy: 0.5204

     58/Unknown - 1s 10ms/step - loss: 0.8593 - accuracy: 0.5356

     64/Unknown - 1s 10ms/step - loss: 0.8425 - accuracy: 0.5415

     70/Unknown - 1s 10ms/step - loss: 0.8301 - accuracy: 0.5458

     76/Unknown - 1s 10ms/step - loss: 0.8169 - accuracy: 0.5498

     82/Unknown - 1s 10ms/step - loss: 0.8032 - accuracy: 0.5547

     88/Unknown - 1s 10ms/step - loss: 0.7909 - accuracy: 0.5584

     94/Unknown - 1s 10ms/step - loss: 0.7803 - accuracy: 0.5638

    100/Unknown - 1s 10ms/step - loss: 0.7712 - accuracy: 0.5683

    106/Unknown - 1s 10ms/step - loss: 0.7631 - accuracy: 0.5733

    112/Unknown - 1s 10ms/step - loss: 0.7521 - accuracy: 0.5812

    118/Unknown - 1s 10ms/step - loss: 0.7469 - accuracy: 0.5849

    124/Unknown - 1s 10ms/step - loss: 0.7415 - accuracy: 0.5893

    130/Unknown - 1s 10ms/step - loss: 0.7348 - accuracy: 0.5947

    136/Unknown - 1s 10ms/step - loss: 0.7314 - accuracy: 0.5981

    142/Unknown - 1s 10ms/step - loss: 0.7265 - accuracy: 0.6012

    148/Unknown - 1s 10ms/step - loss: 0.7218 - accuracy: 0.6066

    154/Unknown - 1s 10ms/step - loss: 0.7176 - accuracy: 0.6093

    160/Unknown - 2s 10ms/step - loss: 0.7170 - accuracy: 0.6103

    166/Unknown - 2s 10ms/step - loss: 0.7120 - accuracy: 0.6140

    172/Unknown - 2s 10ms/step - loss: 0.7074 - accuracy: 0.6178

    178/Unknown - 2s 10ms/step - loss: 0.7051 - accuracy: 0.6200

    184/Unknown - 2s 9ms/step - loss: 0.7006 - accuracy: 0.6237 

    190/Unknown - 2s 9ms/step - loss: 0.6972 - accuracy: 0.6259

    195/Unknown - 2s 10ms/step - loss: 0.6932 - accuracy: 0.6281

    201/Unknown - 2s 10ms/step - loss: 0.6894 - accuracy: 0.6304

    207/Unknown - 2s 10ms/step - loss: 0.6852 - accuracy: 0.6340

    213/Unknown - 2s 10ms/step - loss: 0.6802 - accuracy: 0.6381

    219/Unknown - 2s 9ms/step - loss: 0.6782 - accuracy: 0.6398 

    225/Unknown - 2s 9ms/step - loss: 0.6724 - accuracy: 0.6433

    231/Unknown - 2s 9ms/step - loss: 0.6695 - accuracy: 0.6456

    237/Unknown - 2s 10ms/step - loss: 0.6663 - accuracy: 0.6481

    243/Unknown - 2s 9ms/step - loss: 0.6639 - accuracy: 0.6499 

    249/Unknown - 2s 9ms/step - loss: 0.6596 - accuracy: 0.6524

    255/Unknown - 2s 9ms/step - loss: 0.6559 - accuracy: 0.6547

    261/Unknown - 2s 9ms/step - loss: 0.6534 - accuracy: 0.6567

    267/Unknown - 3s 9ms/step - loss: 0.6499 - accuracy: 0.6593

    273/Unknown - 3s 9ms/step - loss: 0.6473 - accuracy: 0.6615

    279/Unknown - 3s 9ms/step - loss: 0.6451 - accuracy: 0.6631

    285/Unknown - 3s 9ms/step - loss: 0.6421 - accuracy: 0.6650

    291/Unknown - 3s 9ms/step - loss: 0.6386 - accuracy: 0.6675

    297/Unknown - 3s 9ms/step - loss: 0.6359 - accuracy: 0.6691

    303/Unknown - 3s 9ms/step - loss: 0.6327 - accuracy: 0.6710

    309/Unknown - 3s 9ms/step - loss: 0.6289 - accuracy: 0.6739

    315/Unknown - 3s 9ms/step - loss: 0.6258 - accuracy: 0.6764

    321/Unknown - 3s 9ms/step - loss: 0.6246 - accuracy: 0.6772

    327/Unknown - 3s 9ms/step - loss: 0.6225 - accuracy: 0.6785

    333/Unknown - 3s 9ms/step - loss: 0.6201 - accuracy: 0.6798

    339/Unknown - 3s 9ms/step - loss: 0.6169 - accuracy: 0.6816

    345/Unknown - 3s 9ms/step - loss: 0.6149 - accuracy: 0.6832

    351/Unknown - 3s 9ms/step - loss: 0.6114 - accuracy: 0.6853

    357/Unknown - 3s 9ms/step - loss: 0.6086 - accuracy: 0.6869

    363/Unknown - 3s 9ms/step - loss: 0.6060 - accuracy: 0.6885

    369/Unknown - 3s 9ms/step - loss: 0.6038 - accuracy: 0.6900

    375/Unknown - 4s 9ms/step - loss: 0.6015 - accuracy: 0.6915

    381/Unknown - 4s 9ms/step - loss: 0.5993 - accuracy: 0.6934

    387/Unknown - 4s 9ms/step - loss: 0.5969 - accuracy: 0.6949

    393/Unknown - 4s 9ms/step - loss: 0.5938 - accuracy: 0.6970

    399/Unknown - 4s 9ms/step - loss: 0.5924 - accuracy: 0.6980

    405/Unknown - 4s 9ms/step - loss: 0.5906 - accuracy: 0.6988

    411/Unknown - 4s 9ms/step - loss: 0.5889 - accuracy: 0.6999

    417/Unknown - 4s 9ms/step - loss: 0.5869 - accuracy: 0.7013

    423/Unknown - 4s 9ms/step - loss: 0.5848 - accuracy: 0.7031

    429/Unknown - 4s 9ms/step - loss: 0.5830 - accuracy: 0.7044

    435/Unknown - 4s 9ms/step - loss: 0.5814 - accuracy: 0.7052

    441/Unknown - 4s 9ms/step - loss: 0.5792 - accuracy: 0.7065

    447/Unknown - 4s 9ms/step - loss: 0.5779 - accuracy: 0.7075

    452/Unknown - 4s 9ms/step - loss: 0.5763 - accuracy: 0.7088

    458/Unknown - 4s 9ms/step - loss: 0.5744 - accuracy: 0.7101

    464/Unknown - 4s 9ms/step - loss: 0.5725 - accuracy: 0.7112

    470/Unknown - 4s 9ms/step - loss: 0.5702 - accuracy: 0.7127

    476/Unknown - 5s 9ms/step - loss: 0.5682 - accuracy: 0.7142

    482/Unknown - 5s 9ms/step - loss: 0.5667 - accuracy: 0.7150

    488/Unknown - 5s 9ms/step - loss: 0.5645 - accuracy: 0.7165

    494/Unknown - 5s 9ms/step - loss: 0.5627 - accuracy: 0.7179

    500/Unknown - 5s 9ms/step - loss: 0.5613 - accuracy: 0.7188

    506/Unknown - 5s 9ms/step - loss: 0.5604 - accuracy: 0.7194

    512/Unknown - 5s 9ms/step - loss: 0.5585 - accuracy: 0.7206

    518/Unknown - 5s 9ms/step - loss: 0.5571 - accuracy: 0.7214

    524/Unknown - 5s 9ms/step - loss: 0.5554 - accuracy: 0.7227

    530/Unknown - 5s 9ms/step - loss: 0.5543 - accuracy: 0.7235

    536/Unknown - 5s 9ms/step - loss: 0.5526 - accuracy: 0.7246

    542/Unknown - 5s 9ms/step - loss: 0.5510 - accuracy: 0.7254

    548/Unknown - 5s 9ms/step - loss: 0.5493 - accuracy: 0.7264

    554/Unknown - 5s 9ms/step - loss: 0.5481 - accuracy: 0.7272

    560/Unknown - 5s 9ms/step - loss: 0.5466 - accuracy: 0.7282

    566/Unknown - 5s 9ms/step - loss: 0.5457 - accuracy: 0.7287

    572/Unknown - 5s 9ms/step - loss: 0.5445 - accuracy: 0.7293

    578/Unknown - 5s 9ms/step - loss: 0.5432 - accuracy: 0.7303

    583/Unknown - 6s 9ms/step - loss: 0.5421 - accuracy: 0.7308

    589/Unknown - 6s 9ms/step - loss: 0.5407 - accuracy: 0.7318

    595/Unknown - 6s 9ms/step - loss: 0.5389 - accuracy: 0.7330

    601/Unknown - 6s 9ms/step - loss: 0.5377 - accuracy: 0.7337

    607/Unknown - 6s 9ms/step - loss: 0.5360 - accuracy: 0.7348

    613/Unknown - 6s 9ms/step - loss: 0.5349 - accuracy: 0.7354

    619/Unknown - 6s 9ms/step - loss: 0.5334 - accuracy: 0.7365

    625/Unknown - 6s 9ms/step - loss: 0.5326 - accuracy: 0.7370

    631/Unknown - 6s 9ms/step - loss: 0.5310 - accuracy: 0.7379

    637/Unknown - 6s 9ms/step - loss: 0.5301 - accuracy: 0.7386

    643/Unknown - 6s 9ms/step - loss: 0.5286 - accuracy: 0.7396

    649/Unknown - 6s 9ms/step - loss: 0.5276 - accuracy: 0.7402

    655/Unknown - 6s 9ms/step - loss: 0.5265 - accuracy: 0.7408

    661/Unknown - 6s 9ms/step - loss: 0.5253 - accuracy: 0.7414

    667/Unknown - 6s 9ms/step - loss: 0.5238 - accuracy: 0.7423

    672/Unknown - 6s 9ms/step - loss: 0.5229 - accuracy: 0.7429

    678/Unknown - 6s 9ms/step - loss: 0.5221 - accuracy: 0.7434

    684/Unknown - 6s 9ms/step - loss: 0.5210 - accuracy: 0.7441

    690/Unknown - 7s 9ms/step - loss: 0.5196 - accuracy: 0.7448

    696/Unknown - 7s 9ms/step - loss: 0.5183 - accuracy: 0.7456

697/697 [==============================] - 10s 14ms/step - loss: 0.5181 - accuracy: 0.7457 - val_loss: 0.3855 - val_accuracy: 0.8222


Epoch 2/3


  1/697 [..............................] - ETA: 0s - loss: 0.2253 - accuracy: 0.9219

  7/697 [..............................] - ETA: 5s - loss: 0.2646 - accuracy: 0.8929

 13/697 [..............................] - ETA: 5s - loss: 0.2549 - accuracy: 0.8942

 19/697 [..............................] - ETA: 6s - loss: 0.2583 - accuracy: 0.8923

 25/697 [>.............................] - ETA: 6s - loss: 0.2725 - accuracy: 0.8844

 31/697 [>.............................] - ETA: 6s - loss: 0.2747 - accuracy: 0.8770

 37/697 [>.............................] - ETA: 6s - loss: 0.2816 - accuracy: 0.8725

 43/697 [>.............................] - ETA: 6s - loss: 0.2763 - accuracy: 0.8754

 49/697 [=>............................] - ETA: 6s - loss: 0.2726 - accuracy: 0.8782

 55/697 [=>............................] - ETA: 5s - loss: 0.2749 - accuracy: 0.8776

 61/697 [=>............................] - ETA: 5s - loss: 0.2789 - accuracy: 0.8747

 67/697 [=>............................] - ETA: 5s - loss: 0.2799 - accuracy: 0.8731

 73/697 [==>...........................] - ETA: 5s - loss: 0.2790 - accuracy: 0.8741

 79/697 [==>...........................] - ETA: 5s - loss: 0.2820 - accuracy: 0.8724

 85/697 [==>...........................] - ETA: 5s - loss: 0.2804 - accuracy: 0.8730

 91/697 [==>...........................] - ETA: 5s - loss: 0.2843 - accuracy: 0.8705

 97/697 [===>..........................] - ETA: 5s - loss: 0.2862 - accuracy: 0.8702

103/697 [===>..........................] - ETA: 5s - loss: 0.2885 - accuracy: 0.8694

109/697 [===>..........................] - ETA: 5s - loss: 0.2908 - accuracy: 0.8694

115/697 [===>..........................] - ETA: 5s - loss: 0.2936 - accuracy: 0.8686

121/697 [====>.........................] - ETA: 5s - loss: 0.2945 - accuracy: 0.8688

127/697 [====>.........................] - ETA: 5s - loss: 0.2971 - accuracy: 0.8672

133/697 [====>.........................] - ETA: 5s - loss: 0.2985 - accuracy: 0.8665

139/697 [====>.........................] - ETA: 5s - loss: 0.2976 - accuracy: 0.8668

145/697 [=====>........................] - ETA: 5s - loss: 0.2965 - accuracy: 0.8683

151/697 [=====>........................] - ETA: 5s - loss: 0.2964 - accuracy: 0.8684

157/697 [=====>........................] - ETA: 5s - loss: 0.2962 - accuracy: 0.8683

163/697 [======>.......................] - ETA: 4s - loss: 0.2964 - accuracy: 0.8686

169/697 [======>.......................] - ETA: 4s - loss: 0.2963 - accuracy: 0.8689

175/697 [======>.......................] - ETA: 4s - loss: 0.2965 - accuracy: 0.8693

181/697 [======>.......................] - ETA: 4s - loss: 0.2969 - accuracy: 0.8692

187/697 [=======>......................] - ETA: 4s - loss: 0.2972 - accuracy: 0.8687

193/697 [=======>......................] - ETA: 4s - loss: 0.2980 - accuracy: 0.8684

199/697 [=======>......................] - ETA: 4s - loss: 0.2977 - accuracy: 0.8686

205/697 [=======>......................] - ETA: 4s - loss: 0.2969 - accuracy: 0.8691

211/697 [========>.....................] - ETA: 4s - loss: 0.2975 - accuracy: 0.8689

217/697 [========>.....................] - ETA: 4s - loss: 0.2972 - accuracy: 0.8692

223/697 [========>.....................] - ETA: 4s - loss: 0.2972 - accuracy: 0.8693

229/697 [========>.....................] - ETA: 4s - loss: 0.2968 - accuracy: 0.8695

235/697 [=========>....................] - ETA: 4s - loss: 0.2962 - accuracy: 0.8699

241/697 [=========>....................] - ETA: 4s - loss: 0.2969 - accuracy: 0.8693

247/697 [=========>....................] - ETA: 4s - loss: 0.2952 - accuracy: 0.8698

253/697 [=========>....................] - ETA: 4s - loss: 0.2934 - accuracy: 0.8705

259/697 [==========>...................] - ETA: 4s - loss: 0.2942 - accuracy: 0.8708

265/697 [==========>...................] - ETA: 4s - loss: 0.2947 - accuracy: 0.8702

271/697 [==========>...................] - ETA: 3s - loss: 0.2956 - accuracy: 0.8698

277/697 [==========>...................] - ETA: 3s - loss: 0.2952 - accuracy: 0.8700

283/697 [===========>..................] - ETA: 3s - loss: 0.2953 - accuracy: 0.8700

289/697 [===========>..................] - ETA: 3s - loss: 0.2954 - accuracy: 0.8700

295/697 [===========>..................] - ETA: 3s - loss: 0.2946 - accuracy: 0.8701

301/697 [===========>..................] - ETA: 3s - loss: 0.2947 - accuracy: 0.8701

307/697 [============>.................] - ETA: 3s - loss: 0.2950 - accuracy: 0.8698

313/697 [============>.................] - ETA: 3s - loss: 0.2949 - accuracy: 0.8699

319/697 [============>.................] - ETA: 3s - loss: 0.2939 - accuracy: 0.8704

325/697 [============>.................] - ETA: 3s - loss: 0.2938 - accuracy: 0.8704

331/697 [=============>................] - ETA: 3s - loss: 0.2943 - accuracy: 0.8703

337/697 [=============>................] - ETA: 3s - loss: 0.2947 - accuracy: 0.8699

343/697 [=============>................] - ETA: 3s - loss: 0.2947 - accuracy: 0.8702

349/697 [==============>...............] - ETA: 3s - loss: 0.2949 - accuracy: 0.8700

355/697 [==============>...............] - ETA: 3s - loss: 0.2953 - accuracy: 0.8698

361/697 [==============>...............] - ETA: 3s - loss: 0.2949 - accuracy: 0.8698

366/697 [==============>...............] - ETA: 3s - loss: 0.2947 - accuracy: 0.8697

372/697 [===============>..............] - ETA: 3s - loss: 0.2945 - accuracy: 0.8697

378/697 [===============>..............] - ETA: 3s - loss: 0.2946 - accuracy: 0.8697

384/697 [===============>..............] - ETA: 2s - loss: 0.2955 - accuracy: 0.8693

390/697 [===============>..............] - ETA: 2s - loss: 0.2956 - accuracy: 0.8694

396/697 [================>.............] - ETA: 2s - loss: 0.2953 - accuracy: 0.8699

402/697 [================>.............] - ETA: 2s - loss: 0.2954 - accuracy: 0.8699

408/697 [================>.............] - ETA: 2s - loss: 0.2950 - accuracy: 0.8699

414/697 [================>.............] - ETA: 2s - loss: 0.2956 - accuracy: 0.8699

420/697 [=================>............] - ETA: 2s - loss: 0.2964 - accuracy: 0.8694

426/697 [=================>............] - ETA: 2s - loss: 0.2965 - accuracy: 0.8695

432/697 [=================>............] - ETA: 2s - loss: 0.2970 - accuracy: 0.8691

438/697 [=================>............] - ETA: 2s - loss: 0.2972 - accuracy: 0.8691

444/697 [==================>...........] - ETA: 2s - loss: 0.2968 - accuracy: 0.8692

450/697 [==================>...........] - ETA: 2s - loss: 0.2971 - accuracy: 0.8693

456/697 [==================>...........] - ETA: 2s - loss: 0.2973 - accuracy: 0.8693

462/697 [==================>...........] - ETA: 2s - loss: 0.2974 - accuracy: 0.8693

468/697 [===================>..........] - ETA: 2s - loss: 0.2970 - accuracy: 0.8694

474/697 [===================>..........] - ETA: 2s - loss: 0.2971 - accuracy: 0.8695

480/697 [===================>..........] - ETA: 2s - loss: 0.2973 - accuracy: 0.8695

486/697 [===================>..........] - ETA: 1s - loss: 0.2971 - accuracy: 0.8694

492/697 [====================>.........] - ETA: 1s - loss: 0.2978 - accuracy: 0.8692

498/697 [====================>.........] - ETA: 1s - loss: 0.2983 - accuracy: 0.8690

504/697 [====================>.........] - ETA: 1s - loss: 0.2984 - accuracy: 0.8688

510/697 [====================>.........] - ETA: 1s - loss: 0.2985 - accuracy: 0.8686

516/697 [=====================>........] - ETA: 1s - loss: 0.2986 - accuracy: 0.8685

522/697 [=====================>........] - ETA: 1s - loss: 0.2985 - accuracy: 0.8684

528/697 [=====================>........] - ETA: 1s - loss: 0.2987 - accuracy: 0.8686

534/697 [=====================>........] - ETA: 1s - loss: 0.2986 - accuracy: 0.8688

540/697 [======================>.......] - ETA: 1s - loss: 0.2979 - accuracy: 0.8691

546/697 [======================>.......] - ETA: 1s - loss: 0.2982 - accuracy: 0.8690

552/697 [======================>.......] - ETA: 1s - loss: 0.2979 - accuracy: 0.8690

558/697 [=======================>......] - ETA: 1s - loss: 0.2984 - accuracy: 0.8690

564/697 [=======================>......] - ETA: 1s - loss: 0.2987 - accuracy: 0.8688

570/697 [=======================>......] - ETA: 1s - loss: 0.2989 - accuracy: 0.8687

576/697 [=======================>......] - ETA: 1s - loss: 0.2990 - accuracy: 0.8688

582/697 [========================>.....] - ETA: 1s - loss: 0.2992 - accuracy: 0.8687

588/697 [========================>.....] - ETA: 1s - loss: 0.2993 - accuracy: 0.8685

594/697 [========================>.....] - ETA: 0s - loss: 0.2986 - accuracy: 0.8688

600/697 [========================>.....] - ETA: 0s - loss: 0.2984 - accuracy: 0.8688

606/697 [=========================>....] - ETA: 0s - loss: 0.2985 - accuracy: 0.8686

612/697 [=========================>....] - ETA: 0s - loss: 0.2990 - accuracy: 0.8683

618/697 [=========================>....] - ETA: 0s - loss: 0.2991 - accuracy: 0.8683

624/697 [=========================>....] - ETA: 0s - loss: 0.2988 - accuracy: 0.8685

630/697 [==========================>...] - ETA: 0s - loss: 0.2989 - accuracy: 0.8683

636/697 [==========================>...] - ETA: 0s - loss: 0.2992 - accuracy: 0.8681

642/697 [==========================>...] - ETA: 0s - loss: 0.2989 - accuracy: 0.8684

648/697 [==========================>...] - ETA: 0s - loss: 0.2988 - accuracy: 0.8684

654/697 [===========================>..] - ETA: 0s - loss: 0.2990 - accuracy: 0.8681

660/697 [===========================>..] - ETA: 0s - loss: 0.2985 - accuracy: 0.8684

666/697 [===========================>..] - ETA: 0s - loss: 0.2985 - accuracy: 0.8684

672/697 [===========================>..] - ETA: 0s - loss: 0.2984 - accuracy: 0.8684

678/697 [============================>.] - ETA: 0s - loss: 0.2981 - accuracy: 0.8686

684/697 [============================>.] - ETA: 0s - loss: 0.2983 - accuracy: 0.8685

690/697 [============================>.] - ETA: 0s - loss: 0.2982 - accuracy: 0.8687

696/697 [============================>.] - ETA: 0s - loss: 0.2984 - accuracy: 0.8685

697/697 [==============================] - 9s 13ms/step - loss: 0.2985 - accuracy: 0.8685 - val_loss: 0.3635 - val_accuracy: 0.8350


Epoch 3/3


  1/697 [..............................] - ETA: 0s - loss: 0.1130 - accuracy: 1.0000

  7/697 [..............................] - ETA: 5s - loss: 0.2020 - accuracy: 0.9174

 13/697 [..............................] - ETA: 5s - loss: 0.1947 - accuracy: 0.9231

 19/697 [..............................] - ETA: 5s - loss: 0.1950 - accuracy: 0.9211

 25/697 [>.............................] - ETA: 6s - loss: 0.1858 - accuracy: 0.9237

 31/697 [>.............................] - ETA: 5s - loss: 0.1902 - accuracy: 0.9239

 37/697 [>.............................] - ETA: 6s - loss: 0.1905 - accuracy: 0.9236

 43/697 [>.............................] - ETA: 5s - loss: 0.1946 - accuracy: 0.9182

 49/697 [=>............................] - ETA: 5s - loss: 0.2000 - accuracy: 0.9149

 55/697 [=>............................] - ETA: 5s - loss: 0.2036 - accuracy: 0.9131

 61/697 [=>............................] - ETA: 5s - loss: 0.2036 - accuracy: 0.9137

 67/697 [=>............................] - ETA: 5s - loss: 0.2036 - accuracy: 0.9135

 73/697 [==>...........................] - ETA: 5s - loss: 0.2005 - accuracy: 0.9159

 79/697 [==>...........................] - ETA: 5s - loss: 0.1972 - accuracy: 0.9169

 85/697 [==>...........................] - ETA: 5s - loss: 0.1997 - accuracy: 0.9154

 91/697 [==>...........................] - ETA: 5s - loss: 0.2008 - accuracy: 0.9145

 97/697 [===>..........................] - ETA: 5s - loss: 0.2022 - accuracy: 0.9148

103/697 [===>..........................] - ETA: 5s - loss: 0.2006 - accuracy: 0.9150

109/697 [===>..........................] - ETA: 5s - loss: 0.2002 - accuracy: 0.9156

115/697 [===>..........................] - ETA: 5s - loss: 0.1996 - accuracy: 0.9149

121/697 [====>.........................] - ETA: 5s - loss: 0.1987 - accuracy: 0.9154

127/697 [====>.........................] - ETA: 5s - loss: 0.2012 - accuracy: 0.9141

133/697 [====>.........................] - ETA: 5s - loss: 0.2011 - accuracy: 0.9142

139/697 [====>.........................] - ETA: 5s - loss: 0.2014 - accuracy: 0.9139

145/697 [=====>........................] - ETA: 5s - loss: 0.2018 - accuracy: 0.9137

151/697 [=====>........................] - ETA: 5s - loss: 0.2046 - accuracy: 0.9130

157/697 [=====>........................] - ETA: 5s - loss: 0.2048 - accuracy: 0.9122

163/697 [======>.......................] - ETA: 4s - loss: 0.2049 - accuracy: 0.9117

169/697 [======>.......................] - ETA: 4s - loss: 0.2046 - accuracy: 0.9119

175/697 [======>.......................] - ETA: 4s - loss: 0.2061 - accuracy: 0.9115

181/697 [======>.......................] - ETA: 4s - loss: 0.2058 - accuracy: 0.9117

187/697 [=======>......................] - ETA: 4s - loss: 0.2068 - accuracy: 0.9111

193/697 [=======>......................] - ETA: 4s - loss: 0.2072 - accuracy: 0.9110

199/697 [=======>......................] - ETA: 4s - loss: 0.2076 - accuracy: 0.9106

205/697 [=======>......................] - ETA: 4s - loss: 0.2077 - accuracy: 0.9102

211/697 [========>.....................] - ETA: 4s - loss: 0.2073 - accuracy: 0.9105

217/697 [========>.....................] - ETA: 4s - loss: 0.2076 - accuracy: 0.9106

223/697 [========>.....................] - ETA: 4s - loss: 0.2072 - accuracy: 0.9108

229/697 [========>.....................] - ETA: 4s - loss: 0.2074 - accuracy: 0.9108

235/697 [=========>....................] - ETA: 4s - loss: 0.2072 - accuracy: 0.9112

241/697 [=========>....................] - ETA: 4s - loss: 0.2075 - accuracy: 0.9114

247/697 [=========>....................] - ETA: 4s - loss: 0.2066 - accuracy: 0.9118

253/697 [=========>....................] - ETA: 4s - loss: 0.2073 - accuracy: 0.9116

259/697 [==========>...................] - ETA: 4s - loss: 0.2076 - accuracy: 0.9110

265/697 [==========>...................] - ETA: 4s - loss: 0.2074 - accuracy: 0.9112

271/697 [==========>...................] - ETA: 3s - loss: 0.2094 - accuracy: 0.9105

277/697 [==========>...................] - ETA: 3s - loss: 0.2096 - accuracy: 0.9104

283/697 [===========>..................] - ETA: 3s - loss: 0.2104 - accuracy: 0.9102

289/697 [===========>..................] - ETA: 3s - loss: 0.2116 - accuracy: 0.9098

295/697 [===========>..................] - ETA: 3s - loss: 0.2124 - accuracy: 0.9093

301/697 [===========>..................] - ETA: 3s - loss: 0.2129 - accuracy: 0.9094

307/697 [============>.................] - ETA: 3s - loss: 0.2130 - accuracy: 0.9096

313/697 [============>.................] - ETA: 3s - loss: 0.2128 - accuracy: 0.9096

319/697 [============>.................] - ETA: 3s - loss: 0.2129 - accuracy: 0.9095

325/697 [============>.................] - ETA: 3s - loss: 0.2135 - accuracy: 0.9090

331/697 [=============>................] - ETA: 3s - loss: 0.2137 - accuracy: 0.9090

337/697 [=============>................] - ETA: 3s - loss: 0.2141 - accuracy: 0.9087

343/697 [=============>................] - ETA: 3s - loss: 0.2137 - accuracy: 0.9088

349/697 [==============>...............] - ETA: 3s - loss: 0.2143 - accuracy: 0.9087

355/697 [==============>...............] - ETA: 3s - loss: 0.2144 - accuracy: 0.9086

361/697 [==============>...............] - ETA: 3s - loss: 0.2148 - accuracy: 0.9083

367/697 [==============>...............] - ETA: 3s - loss: 0.2149 - accuracy: 0.9083

373/697 [===============>..............] - ETA: 3s - loss: 0.2155 - accuracy: 0.9078

379/697 [===============>..............] - ETA: 2s - loss: 0.2163 - accuracy: 0.9076

385/697 [===============>..............] - ETA: 2s - loss: 0.2170 - accuracy: 0.9073

390/697 [===============>..............] - ETA: 2s - loss: 0.2171 - accuracy: 0.9073

395/697 [================>.............] - ETA: 2s - loss: 0.2171 - accuracy: 0.9071

401/697 [================>.............] - ETA: 2s - loss: 0.2173 - accuracy: 0.9069

407/697 [================>.............] - ETA: 2s - loss: 0.2177 - accuracy: 0.9067

413/697 [================>.............] - ETA: 2s - loss: 0.2178 - accuracy: 0.9066

419/697 [=================>............] - ETA: 2s - loss: 0.2183 - accuracy: 0.9063

425/697 [=================>............] - ETA: 2s - loss: 0.2182 - accuracy: 0.9062

431/697 [=================>............] - ETA: 2s - loss: 0.2182 - accuracy: 0.9062

437/697 [=================>............] - ETA: 2s - loss: 0.2184 - accuracy: 0.9061

443/697 [==================>...........] - ETA: 2s - loss: 0.2186 - accuracy: 0.9061

449/697 [==================>...........] - ETA: 2s - loss: 0.2179 - accuracy: 0.9063

455/697 [==================>...........] - ETA: 2s - loss: 0.2189 - accuracy: 0.9058

461/697 [==================>...........] - ETA: 2s - loss: 0.2190 - accuracy: 0.9059

467/697 [===================>..........] - ETA: 2s - loss: 0.2192 - accuracy: 0.9055

473/697 [===================>..........] - ETA: 2s - loss: 0.2194 - accuracy: 0.9056

479/697 [===================>..........] - ETA: 2s - loss: 0.2195 - accuracy: 0.9055

485/697 [===================>..........] - ETA: 1s - loss: 0.2202 - accuracy: 0.9051

491/697 [====================>.........] - ETA: 1s - loss: 0.2205 - accuracy: 0.9050

497/697 [====================>.........] - ETA: 1s - loss: 0.2206 - accuracy: 0.9047

503/697 [====================>.........] - ETA: 1s - loss: 0.2213 - accuracy: 0.9045

509/697 [====================>.........] - ETA: 1s - loss: 0.2214 - accuracy: 0.9044

515/697 [=====================>........] - ETA: 1s - loss: 0.2211 - accuracy: 0.9044

521/697 [=====================>........] - ETA: 1s - loss: 0.2211 - accuracy: 0.9045

527/697 [=====================>........] - ETA: 1s - loss: 0.2206 - accuracy: 0.9048

533/697 [=====================>........] - ETA: 1s - loss: 0.2204 - accuracy: 0.9049

539/697 [======================>.......] - ETA: 1s - loss: 0.2206 - accuracy: 0.9050

545/697 [======================>.......] - ETA: 1s - loss: 0.2209 - accuracy: 0.9045

551/697 [======================>.......] - ETA: 1s - loss: 0.2209 - accuracy: 0.9045

557/697 [======================>.......] - ETA: 1s - loss: 0.2211 - accuracy: 0.9042

563/697 [=======================>......] - ETA: 1s - loss: 0.2216 - accuracy: 0.9038

569/697 [=======================>......] - ETA: 1s - loss: 0.2218 - accuracy: 0.9039

575/697 [=======================>......] - ETA: 1s - loss: 0.2221 - accuracy: 0.9037

581/697 [========================>.....] - ETA: 1s - loss: 0.2221 - accuracy: 0.9038

587/697 [========================>.....] - ETA: 1s - loss: 0.2225 - accuracy: 0.9036

593/697 [========================>.....] - ETA: 0s - loss: 0.2229 - accuracy: 0.9033

599/697 [========================>.....] - ETA: 0s - loss: 0.2230 - accuracy: 0.9032

605/697 [=========================>....] - ETA: 0s - loss: 0.2231 - accuracy: 0.9030

611/697 [=========================>....] - ETA: 0s - loss: 0.2234 - accuracy: 0.9029

617/697 [=========================>....] - ETA: 0s - loss: 0.2233 - accuracy: 0.9028

623/697 [=========================>....] - ETA: 0s - loss: 0.2233 - accuracy: 0.9028

629/697 [==========================>...] - ETA: 0s - loss: 0.2234 - accuracy: 0.9027

635/697 [==========================>...] - ETA: 0s - loss: 0.2237 - accuracy: 0.9028

641/697 [==========================>...] - ETA: 0s - loss: 0.2239 - accuracy: 0.9028

647/697 [==========================>...] - ETA: 0s - loss: 0.2241 - accuracy: 0.9026

653/697 [===========================>..] - ETA: 0s - loss: 0.2238 - accuracy: 0.9026

659/697 [===========================>..] - ETA: 0s - loss: 0.2237 - accuracy: 0.9028

665/697 [===========================>..] - ETA: 0s - loss: 0.2234 - accuracy: 0.9030

671/697 [===========================>..] - ETA: 0s - loss: 0.2237 - accuracy: 0.9028

677/697 [============================>.] - ETA: 0s - loss: 0.2236 - accuracy: 0.9028

683/697 [============================>.] - ETA: 0s - loss: 0.2241 - accuracy: 0.9026

689/697 [============================>.] - ETA: 0s - loss: 0.2241 - accuracy: 0.9026

695/697 [============================>.] - ETA: 0s - loss: 0.2244 - accuracy: 0.9026

697/697 [==============================] - 9s 13ms/step - loss: 0.2242 - accuracy: 0.9027 - val_loss: 0.3794 - val_accuracy: 0.8246


In [22]:
eval_loss, eval_acc = model.evaluate(test_data)

print('\nEval loss: {}, Eval accuracy: {}'.format(eval_loss, eval_acc))

      1/Unknown - 0s 458us/step - loss: 0.3041 - accuracy: 0.8125

      4/Unknown - 0s 14ms/step - loss: 0.3977 - accuracy: 0.8164 

      7/Unknown - 0s 16ms/step - loss: 0.3820 - accuracy: 0.8170

     10/Unknown - 0s 16ms/step - loss: 0.3954 - accuracy: 0.8250

     13/Unknown - 0s 17ms/step - loss: 0.4060 - accuracy: 0.8125

     16/Unknown - 0s 17ms/step - loss: 0.3974 - accuracy: 0.8164

     19/Unknown - 0s 18ms/step - loss: 0.3877 - accuracy: 0.8240

     22/Unknown - 0s 18ms/step - loss: 0.3899 - accuracy: 0.8210

     25/Unknown - 0s 18ms/step - loss: 0.3831 - accuracy: 0.8231

     28/Unknown - 0s 18ms/step - loss: 0.3762 - accuracy: 0.8265

     31/Unknown - 1s 18ms/step - loss: 0.3841 - accuracy: 0.8221

     34/Unknown - 1s 18ms/step - loss: 0.3819 - accuracy: 0.8235

     37/Unknown - 1s 18ms/step - loss: 0.3771 - accuracy: 0.8269

     40/Unknown - 1s 18ms/step - loss: 0.3760 - accuracy: 0.8273

     43/Unknown - 1s 18ms/step - loss: 0.3823 - accuracy: 0.8256

     46/Unknown - 1s 18ms/step - loss: 0.3867 - accuracy: 0.8244

     49/Unknown - 1s 18ms/step - loss: 0.3837 - accuracy: 0.8272

     52/Unknown - 1s 18ms/step - loss: 0.3884 - accuracy: 0.8257

     55/Unknown - 1s 18ms/step - loss: 0.3833 - accuracy: 0.8276

     58/Unknown - 1s 18ms/step - loss: 0.3851 - accuracy: 0.8254

     61/Unknown - 1s 18ms/step - loss: 0.3842 - accuracy: 0.8253

     64/Unknown - 1s 18ms/step - loss: 0.3812 - accuracy: 0.8262

     67/Unknown - 1s 18ms/step - loss: 0.3791 - accuracy: 0.8270

     70/Unknown - 1s 18ms/step - loss: 0.3795 - accuracy: 0.8254

     73/Unknown - 1s 18ms/step - loss: 0.3808 - accuracy: 0.8251

     76/Unknown - 1s 18ms/step - loss: 0.3793 - accuracy: 0.8257

     79/Unknown - 1s 18ms/step - loss: 0.3794 - accuracy: 0.8246

79/79 [==============================] - 1s 18ms/step - loss: 0.3794 - accuracy: 0.8246



Eval loss: 0.3794495761394501, Eval accuracy: 0.8245999813079834
